{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "b6ef4e75_f083f343",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1000000
      },
      "writtenOn": "2021-02-11T12:11:25Z",
      "side": 1,
      "message": "recheck",
      "revId": "d75c2f914fe219aa46c9a599ec28bc13e91052ae",
      "serverId": "e32f8df8-3db0-4f76-a6c6-fe9d6e69dd68"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "b81f4c91_93172816",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1000000
      },
      "writtenOn": "2021-02-11T12:34:35Z",
      "side": 1,
      "message": "With this patch in place, boost::process should be able to launch child processes without that error from the locale_facet. Does it work for you?",
      "revId": "d75c2f914fe219aa46c9a599ec28bc13e91052ae",
      "serverId": "e32f8df8-3db0-4f76-a6c6-fe9d6e69dd68"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "1b11c07c_33a992c5",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1000056
      },
      "writtenOn": "2021-02-11T14:08:49Z",
      "side": 1,
      "message": "I cherrypicked this on my firewall patch and it works.",
      "parentUuid": "b81f4c91_93172816",
      "revId": "d75c2f914fe219aa46c9a599ec28bc13e91052ae",
      "serverId": "e32f8df8-3db0-4f76-a6c6-fe9d6e69dd68"
    }
  ]
}