{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "216ae300_4e3e60d7",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 7
      },
      "lineNbr": 0,
      "author": {
        "id": 1000000
      },
      "writtenOn": "2024-07-22T09:08:17Z",
      "side": 1,
      "message": "Just for the record, the merge failure was (probably) triggered by https://gerrit.cesnet.cz/c/CzechLight/dependencies/+/7331/1 pulled in directly via Depends-On, and by https://gerrit.cesnet.cz/c/CzechLight/dependencies/+/7234/12 pulled in through Depends-On in another repo. Because 7331,1 was not a child of 7234,12, the merger complained in its debug log:\n \n2024-07-22 10:44:29,181 DEBUG zuul.Merger: [e: 9961843d19ad41359fc039058144e5de] Merging for change 7331,1\n2024-07-22 10:44:29,181 DEBUG zuul.Merger: [e: 9961843d19ad41359fc039058144e5de] Processing ref refs/changes/31/7331/1 for project cesnet-gerrit-public/CzechLight/dependencies / master uuid 225e95d45f084f4fad8feffced48af0f\n2024-07-22 10:44:29,181 DEBUG zuul.Merger: [e: 9961843d19ad41359fc039058144e5de] Found base commit 9c03f02f43c1e8bf79afde1cb222908980507ec4 for (\u0027cesnet-gerrit-public\u0027, \u0027CzechLight/dependencies\u0027, \u0027master\u0027)\n2024-07-22 10:44:29,183 DEBUG zuul.Repo: [e: 9961843d19ad41359fc039058144e5de] Updating remote reference origin/master to 9c03f02f43c1e8bf79afde1cb222908980507ec4\n2024-07-22 10:44:29,184 DEBUG zuul.Repo: [e: 9961843d19ad41359fc039058144e5de] Checking out 9c03f02f43c1e8bf79afde1cb222908980507ec4\n2024-07-22 10:44:30,187 DEBUG zuul.Repo: [e: 9961843d19ad41359fc039058144e5de] Merging refs/changes/31/7331/1 with args [\u0027-s\u0027, \u0027resolve\u0027, \u0027FETCH_HEAD\u0027]\n2024-07-22 10:44:30,213 DEBUG zuul.Merger: [e: 9961843d19ad41359fc039058144e5de] Merging for change 7234,12\n2024-07-22 10:44:30,213 DEBUG zuul.Merger: [e: 9961843d19ad41359fc039058144e5de] Processing ref refs/changes/34/7234/12 for project cesnet-gerrit-public/CzechLight/dependencies / master uuid de875dabaa8049238249808ca5bde95a\n2024-07-22 10:44:30,213 DEBUG zuul.Merger: [e: 9961843d19ad41359fc039058144e5de] Found base commit 32699bbf74f45dbc94368e2b5bc79e0d4e4fba54 for (\u0027cesnet-gerrit-public\u0027, \u0027CzechLight/dependencies\u0027, \u0027master\u0027)\n2024-07-22 10:44:30,215 DEBUG zuul.Repo: [e: 9961843d19ad41359fc039058144e5de] Updating remote reference origin/master to 32699bbf74f45dbc94368e2b5bc79e0d4e4fba54\n2024-07-22 10:44:30,216 DEBUG zuul.Repo: [e: 9961843d19ad41359fc039058144e5de] Checking out 32699bbf74f45dbc94368e2b5bc79e0d4e4fba54\n2024-07-22 10:44:30,389 DEBUG zuul.Repo: [e: 9961843d19ad41359fc039058144e5de] Merging refs/changes/34/7234/12 with args [\u0027-s\u0027, \u0027resolve\u0027, \u0027FETCH_HEAD\u0027]\n2024-07-22 10:44:30,451 DEBUG zuul.Merger: [e: 9961843d19ad41359fc039058144e5de] Unable to merge {\u0027project\u0027: \u0027CzechLight/dependencies\u0027, \u0027connection\u0027: \u0027cesnet-gerrit-public\u0027, \u0027merge_mode\u0027: 2, \u0027ref\u0027: \u0027refs/changes/34/7234/12\u0027, \u0027branch\u0027: \u0027master\u0027, \u0027buildset_uuid\u0027: \u0027de875dabaa8049238249808ca5bde95a\u0027, \u0027number\u0027: \u00277234\u0027, \u0027patchset\u0027: \u002712\u0027, \u0027oldrev\u0027: None, \u0027newrev\u0027: None}\nTraceback (most recent call last):\n  File \"/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/zuul/merger/merger.py\", line 800, in _mergeChange\n    zuul_event_id\u003dzuul_event_id)\n  File \"/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/zuul/merger/merger.py\", line 480, in merge\n    repo.git.merge(*args)\n  File \"/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/git/cmd.py\", line 548, in \u003clambda\u003e\n    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)\n  File \"/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/git/cmd.py\", line 1014, in _call_process\n    return self.execute(call, **exec_kwargs)\n  File \"/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/git/cmd.py\", line 825, in execute\n    raise GitCommandError(command, status, stderr_value, stdout_value)\ngit.exc.GitCommandError: Cmd(\u0027git\u0027) failed due to: exit code(1)\n  cmdline: git merge -s resolve FETCH_HEAD\n  stdout: \u0027Trying really trivial in-index merge...\nNope.\nTrying simple merge.\nSimple merge failed, trying Automatic merge.\nAutomatic merge failed; fix conflicts and then commit the result.\u0027\n  stderr: \u0027error: Merge requires file-level merging\nERROR: libyang: Not merging conflicting submodule changes.\nERROR: libyang-cpp: Not merging conflicting submodule changes.\nERROR: sysrepo: Not merging conflicting submodule changes.\nERROR: sysrepo-cpp: Not merging conflicting submodule changes.\nfatal: merge program failed\u0027\n\nThe proper fix is just to use linear history in CzechLight/dependencies, which was my intention in 7331 anyway.",
      "revId": "f968b554dbffc266e2126cf212fca2e19b889824",
      "serverId": "e32f8df8-3db0-4f76-a6c6-fe9d6e69dd68"
    }
  ]
}